{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "activepieces.fullname" . }}-redis
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "activepieces.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
