apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.fullname" . }}-secrets
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
type: Opaque
stringData:
  ap-encryption-key: {{ .Values.activepieces.encryptionKey | quote }}
  ap-jwt-secret: {{ .Values.activepieces.jwtSecret | quote }}
  ap-postgres-password: {{ .Values.activepieces.postgres.password | quote }}
  ap-redis-password: {{ .Values.activepieces.redis.password | quote }}
