apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portarium-control-plane
  namespace: portarium
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.local.portarium.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portarium-control-plane
                port:
                  number: 8080
