apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/your-org/portarium-control-plane
    newTag: prod-latest
  - name: ghcr.io/your-org/portarium-worker
    newTag: prod-latest

patchesStrategicMerge:
  - patches/replicas.yaml
