{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otel-collector.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
type: Opaque
stringData:
  TEMPO_ENDPOINT: {{ .Values.secret.tempoEndpoint | quote }}
  TEMPO_AUTH_TOKEN: {{ .Values.secret.tempoAuthToken | quote }}
  PROM_REMOTE_WRITE_URL: {{ .Values.secret.promRemoteWriteUrl | quote }}
  PROM_AUTH_TOKEN: {{ .Values.secret.promAuthToken | quote }}
  LOKI_ENDPOINT: {{ .Values.secret.lokiEndpoint | quote }}
  LOKI_AUTH_TOKEN: {{ .Values.secret.lokiAuthToken | quote }}
{{- end }}
